### PR TITLE
Add Kaeru with English patch

### PR DESCRIPTION
**Pull request by JonAbrams**

### CODE REVIEW

**Review by JoseJX — COMMENTED** [review]
I don't think it's really useful to add the MD5 for these because it isn't a separate patch. You would have to provide the capability to apply the translation patch as well in your application and then I'd have to test and provide translations as available, for every option that's available. Maybe there's a better way to do it, but I'm not sure I want to add this. I'll think about it I guess, but I suspect that it's more effort than what you're proposing here. I'd definitely have to go back and address every single translation patch that's available for the games I've done already.

**Comment by JonAbrams** [comment]
This adds a patch that includes both the translation and yours (so in a sense, it's an alternative to the one already there). That way, users don't need to apply two patches, which is a huge convenience for users of [retropatcher](https://retropatcher.jonabrams.com/), since it (currently?) only lets users apply a single patch.

And we need not necessarily do one of these for every rom with a translation, at least not all at once.

**Comment by JoseJX** [comment]
Right, but what I'm saying is that if you do this for one, then we'd need to do it for all of them. Should we include patches for languages other than English as well? I think it would be better to improve your tool to allow an additional patch, maybe extracting them from the links on my page as well? I'm honestly not sure what's best. Personally, I would prefer to point out where the patches are available rather than distribute them myself.

**Comment by JonAbrams** [comment]
That’s totally fair. I’ll look into it further from my end.

**Comment by JoseJX** [comment]
No worries, and I'm happy to try to make things easier on your end! I'm just trying to limit the amount of work I have to do on my end so that I can keep churning out patches :)

I'm also perfectly fine with you hosting the combined patches yourself as long as there's credit to both the translator and myself.

**Comment by JoseJX** [comment]
I ended up just including the patched MD5. I was being stubborn, sorry! It is definitely more work on my end though :(

I still would rather that people patch the ROM themselves to get the translation so that they're seeing that work as well, but I think this will help.

**Pull request closed without merging**
